[database]
supabase = "managed" # or "local" - for now, only use managed.

[apis]
enabled = true

[api.nudenet]
type = "external" # default is "internal" - since this is external, we depend on the docker container to be running
enabled = true

[api.facelandmarks]
type = "external"
enabled = true

[api.create-video] # this is an internal API (i.e. It runs on the NextJS app)
enabled = false